### ISSUE TITLE
Another way to configure linux (Kconfig, ebuild)

### ISSUE THREAD

**Issue by jollheef** [gg7/gentoo-kernel-guide#1]
Hello,

Today I found you repository and I think my similar work may be interesting for you. I have always thought that configure kernel with  _make nconfig_ is not a **true** gentoo-way, so I started to solve this problem recently.

Previous time (which I explain in my [blog post](https://seccomp.ru/1504674078_how_build_kernel.html)  from 06.09.2017) I was using _Kconfig_ file create by myself. I've described my blogpost shortly because the original post is in russian. We just need to create _Kconfig_ like that:

```
 config LENOVO_G500
    bool "Lenovo G500"
    default y

    # crypto
    select DM_CRYPT
    select CRYPTO_AES_NI_INTEL
    select CRYPTO_USER_API_SKCIPHER
    ...
```

and include it to the main _Kconfig_ file for kernel:

```
# echo 'source "../local/Kconfig"' >> /usr/src/linux/Kconfig
```

So we have native way to get own configuration with documentation and native configuration hierarchy. The only disadvantage is that you can't use it to select option as module, but typically I build kernel without modules so it's wasn't problem for me. 

## Ebuild

Nowadays I use same thing but inside ebuild, which works in the same way:

https://github.com/jollheef/jollheef-overlay/blob/master/sys-kernel/linux/linux-4.17.4.ebuild

**Comment by gg7** [comment]
Hi @jollheef ,

Thanks for the suggestion. I knew about this approach from https://dev.gentoo.org/~mpagano/genpatches/trunk/4.12/4567_distro-Gentoo-Kconfig.patch (which the readme already links to), but you've made it even simpler than that.

I also like that you use an ebuild -- I should link to your overlay as an example.

> The only disadvantage is that you can't use it to select option as module, but typically I build kernel without modules so it's wasn't problem for me.

That's a deal breaker for me.

> Nowadays I use same thing but inside ebuild, which works in the same way:

If you press 'y' on github, you'll get a permalink which won't break after a while.

Permalink for future reference: https://github.com/jollheef/jollheef-overlay/blob/3a59396be2cbbdb1202e30ac577c3676fa5d9a85/sys-kernel/linux/linux-4.17.4.ebuild

I see that you've adopted the `scripts/config` approach in your [later ebuilds](https://github.com/jollheef/jollheef-overlay/blob/9d6326a3f3a52587ca0d1a90bcb12c38c51fc30b/sys-kernel/linux/linux-4.18.6.ebuild). Nice! I like how you enable certain options depending on use flags. Much better than [gentoo-sources](https://github.com/gentoo/gentoo/blob/4973f380c7236c9adff7ee00ada029e8fcf21bba/sys-kernel/gentoo-sources/gentoo-sources-4.18.6.ebuild).

Have you considered sending a pull request to the official gentoo repo?

**Comment by jollheef** [comment]
> Have you considered sending a pull request to the official gentoo repo?

If a lot of people start to use it – yes, I will try to send it to official gentoo repo.

Currently I think that nobody will merge it.
