### ISSUE TITLE
Do you have any plan to provide translated versions?

### ISSUE THREAD

**Issue by ghost** [gg7/gentoo-kernel-guide#2]
This was really helpful, and I want to provide the Korean version, so other Korean people who can't read English also get some useful help.
If you allow me I'll translate and send it to you!

**Comment by gg7** [comment]
Hi @whjeon329! Glad to hear it was useful. You're welcome to translate it, as long as you provide attribution. I'd prefer you to host it yourself instead of merging it here -- less maintenance for me to do this way :)

**Comment by ghost** [comment]
> I'd prefer you to host it yourself instead of merging it here -- less maintenance for me to do this way :)

Ok, I'll post the URL of the translated version (just for your checking purpose if anything's wrong or abused), when I finish the translation. It willl take 1-2 weeks max. Thanks!

**Comment by ghost** [comment]
https://withjeon.com/gentoo-kernel-guide-ko/

Korean translated version is completed.
My comments only appears on top of the post, and nothing was fixed inside the main contents(clearly divided with horizontal line).

Thanks you.

**Comment by gg7** [comment]
Thanks, I've added a link.
